### ISSUE TITLE
Add example to README

### ISSUE THREAD

**Issue by totten** [ginkgostreet/org.civicrm.angularprofiles#4]
This sounds like a useful function. Would it be easy to add an example of how you'd write Angular JS/HTML which uses it?

**Comment by universalhandle** [comment]
Good idea, @totten. @TobiasLounsbury, could you please do this when you find a few minutes?

**Comment by TobiasLounsbury** [comment]
Pull Request created with updates to the readme: https://github.com/ginkgostreet/org.civicrm.angularprofiles/pull/5
