### ISSUE TITLE
Pre-install on demo site?

### ISSUE THREAD

**Issue by eileenmcnaughton** [ginkgostreet/org.civicrm.angularprofiles#8]
I just went to dmaster.demo & got an error about this being needed - perhaps it should be added to the buildkit profile?

**Comment by universalhandle** [comment]
Thanks, Eileen. Yes, it's on my checklist.

**Comment by universalhandle** [comment]
Closing this as MZD [resolved it](https://github.com/civicrm/civicrm-buildkit/pull/225) some time ago.
