### ISSUE TITLE
new version of civicrm plus this module, errors on registering for volunteer opportunity

### ISSUE THREAD

**Issue by DrCord** [ginkgostreet/org.civicrm.angularprofiles#9]
new version of civicrm plus this module, errors on registering for volunteer opportunity

**Comment by DrCord** [comment]
URL:

http://coderdojo.cordslatton.com/civicrm/event/info?reset=1&id=

backTrace

#0 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Core/Error.php(360): CRM_Core_Error::backtrace()
#1 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Utils/Type.php(371): CRM_Core_Error::fatal("id (value: ) is not of the type Positive")
#2 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Utils/Request.php(85): CRM_Utils_Type::validate("", "Positive", TRUE, "id")
#3 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Event/Page/EventInfo.php(52): CRM_Utils_Request::retrieve("id", "Positive", Object(CRM_Event_Page_EventInfo), TRUE)
#4 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Core/Invoke.php(312): CRM_Event_Page_EventInfo->run((Array:3), NULL)
#5 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:15))
#6 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#7 /home1/biodelic/public_html/coderdojo/sites/all/modules/contrib/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#8 [internal function](): civicrm_invoke("event", "info")
#9 /home1/biodelic/public_html/coderdojo/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#10 /home1/biodelic/public_html/coderdojo/index.php(21): menu_execute_active_handler()
#11 {main}
Sorry but we are not able to provide this at the moment.
id (value: ) is not of the type Positive
Return to home page.

**Comment by DrCord** [comment]
Looks like tp me that the id is not being passed correctly in the submit link. you do however get registered successfully, weird problem...hopefully you can fix it soon as this makes the module unusable.

**Comment by axon-obriend** [comment]
Are you using CiviCRM 4.7? There are still a couple of issues affecting compatibility with 4.7.

**Comment by DrCord** [comment]
4.6.12 as the civivolunteer extension is not available for 4.7

**Comment by universalhandle** [comment]
@DrCord, this problem does not appear to be related to Angular Profiles but to CiviVolunteer itself. Could you please post an issue in [that extension's queue](https://issues.civicrm.org/jira/secure/CreateIssue!default.jspa) and give more detailed steps to how to recreate the problem? Thanks!
